#!/usr/bin/env python3
"""
Verification Script for Investigation Story Generation & MongoDB Storage
"""
import asyncio
import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

from app.db.mongodb import connect_to_mongo, get_database, close_mongo_connection
from app.core.story_generator import generate_case_investigation_story

async def test_story_generation():
    print("=" * 80)
    print("RAKSHAK INVESTIGATION STORY GENERATION VERIFICATION")
    print("=" * 80)

    await connect_to_mongo()
    db = get_database()
    if db is None:
        print("[ERROR] Database connection failed.")
        sys.exit(1)

    test_case = "C0001"
    print(f"\n[TEST] Generating Investigation Story for active case '{test_case}'...")
    
    story = await generate_case_investigation_story(case_id=test_case, generated_by="Verification Test Runner")

    print("\n--- STORY METADATA ---")
    print(f"  Story ID     : {story.get('story_id')}")
    print(f"  Case ID      : {story.get('case_id')}")
    print(f"  Title        : {story.get('title')}")
    print(f"  Generated At : {story.get('generated_at')}")
    print(f"  Generated By : {story.get('generated_by')}")
    print(f"  Items Count  : {len(story.get('items', []))}")
    print(f"  Summary      : {story.get('summary')[:150]}...")

    print("\n--- SAMPLE CHRONOLOGICAL STORY ITEMS (FACT vs INFERENCE) ---")
    items = story.get("items", [])
    for idx, item in enumerate(items[:5], 1):
        print(f"\n  [{item.get('sequence')}] Timestamp: {item.get('timestamp')}")
        print(f"      Source           : {item.get('source_type')} ({item.get('source_record_id')})")
        print(f"      Fact / Inference : {item.get('fact_or_inference')}")
        print(f"      Observation      : {item.get('observation')}")
        print(f"      Supporting Evid  : {item.get('supporting_evidence')}")
        print(f"      Hypothesis       : {item.get('hypothesis')} (Confidence: {int(item.get('confidence', 0)*100)}%)")
        print(f"      Contradictions   : {item.get('contradicting_evidence')}")
        print(f"      Next Action      : {item.get('next_investigative_action')}")

    # Verify MongoDB persistence
    db_story = await db.investigation_stories.find_one({"case_id": test_case}, {"_id": 0})
    db_items_count = await db.investigation_story_items.count_documents({"case_id": test_case})

    print("\n--- MONGODB PERSISTENCE VERIFICATION ---")
    print(f"  investigation_stories record found      : {bool(db_story)}")
    print(f"  investigation_story_items documents     : {db_items_count}")

    assert db_story is not None, "FAILED: Story document not found in investigation_stories!"
    assert db_items_count > 0, "FAILED: Zero items in investigation_story_items!"

    print("\n[VERIFICATION SUCCESS] Investigation Story generation and MongoDB persistence verified!")
    await close_mongo_connection()

if __name__ == "__main__":
    asyncio.run(test_story_generation())
